FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn config set network-timeout 600000 -g \
  && yarn config set network-concurrency 4 -g \
  && yarn install --frozen-lockfile

EXPOSE 5173

CMD ["yarn", "dev", "--host", "0.0.0.0"]
